name: ag
description: Flutter-модуль проекта "Активный Гражданин"
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.22.0
  share:
    path: plugins/share
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  flutter_html: ^2.1.5
  intl: ^0.17.0
  uni_links: ^0.5.1
  uuid: ^3.0.4
  device_info: ^2.0.2
  http: ^0.13.3
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  kiwi: ^3.0.0
  url_launcher: ^6.0.9
  logger: ^1.0.0
  flutter_spinkit: ^5.0.0
  keyboard_actions: ^3.4.0
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  permission_handler: ^8.3.0
  flutter_secure_storage: ^4.2.0
  shared_preferences:
    path: plugins/shared_preferences
  flutter_inappwebview:
    path: plugins/flutter_inappwebview
  dart_json:
    path: plugins/dart-json
  f_logs: ^2.0.0
  flutter_widget_from_html: ^0.6.1
  scroll_to_index: ^2.0.0
  photo_view: ^0.12.0
  flutter_localizations:
    sdk: flutter
  package_info: ^2.0.2
  jiffy: ^4.1.0
  throttling: ^1.0.0
  flutter_inner_drawer: ^1.0.0+1
  intersperse: ^2.0.0
  qr: ^2.1.0
  synchronized: ^3.0.0
  mask_text_input_formatter: ^2.0.0
  image_picker: 
    path: plugins/image_picker
  image_cropper:
    path: plugins/flutter_image_cropper
  version: ^2.0.0
  oktoast: ^3.0.0
  focus_detector: ^1.1.0+1
  super_tooltip: ^1.0.1
  flutter_map: ^0.13.1
  youtube_player_iframe: ^2.2.2
  chewie: ^1.2.2
  video_player: ^2.2.6
  geolocator: 8.0.1
  flutter_js: ^0.5.0+5

dev_dependencies:
  test_kit:
    path: plugins/test_kit
  build_runner: ^2.0.5
  bloc_test: ^8.0.2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dependency_overrides: 
  flutter_inappwebview:
    path: plugins/flutter_inappwebview
  webview_flutter: 2.3.1
  webview_flutter_wkwebview: 2.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/poll_categories/
    - assets/images/poll_details_header/
    - assets/images/other_project_logos/
    - assets/svg/
    - assets/svg/icons/
    - assets/svg/social_icons/

  module:
    androidX: true
    androidPackage: ru.mos.ag
    iosBundleIdentifier: ru.mos.ag
